"""More sauces, spices and condiments for the Sauces & spices guide.

Same shape as library.TASTE_GUIDE items: (name, jp, kcal, serving, use, where, allergens, yen).
Sections with a key that already exists are merged into it; new keys become new sections.
"""

EXTRA_GUIDE = [
    ("make", "Make it yourself", "", "", [
        ("Lemon garlic yogurt", "", 15, "1 tbsp", "Yogurt + lemon + grated garlic + salt. For grilled chicken, kebabs, potatoes.", "Make it", "dairy", 0),
        ("Chimichurri (light)", "", 25, "1 tbsp", "Parsley + garlic + vinegar + chili + 1 tsp oil for the whole jar. For steak and chicken.", "Make it", "", 0),
        ("Green onion ginger oil (light)", "", 30, "1 tbsp", "Lots of green onion + ginger + salt, pour 1 tbsp hot oil over. For chicken and rice.", "Make it", "", 0),
        ("Peanut sauce (light)", "", 35, "1 tbsp", "1 tsp peanut butter + soy + lime + hot water + chili. For noodles and chicken skewers.", "Make it", "peanut, soy, wheat", 0),
        ("Honey mustard (light)", "", 20, "1 tbsp", "Mustard + a little honey + yogurt. For chicken tenders and salads.", "Make it", "dairy", 0),
        ("Sweet chili (no sugar)", "", 8, "1 tbsp", "Vinegar + chili flakes + garlic + sweetener + pinch of starch. For gyoza and chicken.", "Make it", "", 0),
        ("Pico de gallo", "", 5, "2 tbsp", "Tomato + onion + cilantro + lime + salt. On eggs, tacos, rice bowls.", "Make it", "", 0),
        ("Garlic soy glaze", "", 15, "1 tbsp", "Soy + garlic + sweetener + water + starch, simmer. For chicken thighs and tofu.", "Make it", "soy, wheat", 0),
        ("Buffalo yogurt dip", "", 20, "2 tbsp", "Hot sauce stirred into yogurt. For air-fried chicken.", "Make it", "dairy", 0),
        ("Raita", "", 15, "2 tbsp", "Yogurt + cucumber + cumin + mint. Cools down any curry.", "Make it", "dairy", 0),
        ("Salsa verde (light)", "", 20, "1 tbsp", "Parsley + capers + lemon + garlic + 1 tsp oil. For fish and potatoes.", "Make it", "", 0),
        ("Miso mayo (light)", "", 25, "1 tbsp", "Half-calorie mayo + miso. For salmon, corn, cabbage.", "Make it", "egg, soy", 0),
        ("Yakiniku dip (light)", "", 15, "1 tbsp", "Soy + garlic + apple purée + sesame. For beef and pork.", "Make it", "soy, wheat, sesame", 0),
        ("Cilantro lime crema", "", 15, "2 tbsp", "Yogurt + lime + cilantro + salt. For burrito bowls.", "Make it", "dairy", 0),
        ("Tahini lemon (light)", "", 30, "1 tbsp", "1 tsp tahini + lemon + water + garlic. For chickpeas and roast veg.", "Make it", "sesame", 0),
        ("Ume shiso dressing", "", 10, "1 tbsp", "Mashed umeboshi + shiso + rice vinegar. For pork shabu and tofu.", "Make it", "", 0),
    ]),
    ("buy", "Sauces to buy", "", "", [
        ("Oyster sauce", "", 15, "1 tbsp", "Savory-sweet for stir-fries and broccoli.", "Supermarket", "shellfish, wheat", 250),
        ("Hoisin", "", 35, "1 tbsp", "Sweet-savory glaze for pork and lettuce wraps. Use a little.", "Supermarket", "soy, wheat", 350),
        ("Gochujang", "", 30, "1 tbsp", "Korean chili paste for bibimbap, stews, marinades.", "Supermarket", "soy, wheat", 400),
        ("Doubanjiang", "", 15, "1 tsp", "Spicy bean paste for mapo tofu and stir-fries.", "Supermarket", "soy, wheat", 300),
        ("Tonkatsu sauce", "", 20, "1 tbsp", "Fruity brown sauce for cutlets and cabbage.", "Supermarket", "", 250),
        ("Worcestershire sauce", "", 15, "1 tbsp", "Tangy depth for hamburg steak and fried rice.", "Supermarket", "fish", 250),
        ("Okonomi sauce", "", 25, "1 tbsp", "For okonomiyaki, yakisoba, takoyaki.", "Supermarket", "", 300),
        ("Yakiniku sauce", "", 25, "1 tbsp", "Grilled meat dip; pick a light one.", "Supermarket", "soy, wheat, sesame", 300),
        ("Sesame dressing (light)", "", 35, "1 tbsp", "Creamy goma dressing, light version.", "Supermarket", "sesame, soy, egg", 300),
        ("Salsa (jar)", "", 5, "2 tbsp", "On eggs, chicken, rice. Almost free calories.", "Kaldi", "", 450),
        ("Hot sauce (Frank's style)", "", 0, "1 tsp", "Buffalo flavour for chicken.", "Kaldi", "", 500),
        ("Chili crisp", "", 45, "1 tsp", "Crunchy chili oil. A little goes far on eggs and noodles.", "Supermarket", "soy, sesame", 400),
        ("Rayu", "", 40, "1 tsp", "Chili oil for gyoza dip and ramen.", "Supermarket", "sesame", 200),
        ("BBQ sauce (low sugar)", "", 15, "1 tbsp", "For pulled chicken and air-fried wings.", "Kaldi", "", 450),
        ("Pesto", "", 70, "1 tbsp", "Rich; thin it with lemon and water for pasta.", "Supermarket", "dairy, nuts", 400),
        ("Teriyaki sauce", "", 30, "1 tbsp", "Ready-made glaze; use half and add water.", "Supermarket", "soy, wheat", 250),
        ("Sukiyaki sauce", "", 30, "1 tbsp", "Sweet soy for beef and tofu hot pot.", "Supermarket", "soy, wheat", 300),
        ("Mustard", "", 5, "1 tsp", "Dijon or karashi. Sharp flavour for zero calories.", "Supermarket", "", 200),
        ("Light soy sauce", "", 8, "1 tbsp", "Less salty soy for every day.", "Supermarket", "soy, wheat", 250),
        ("Mirin", "", 40, "1 tbsp", "Sweet rice seasoning; half a spoon is usually enough.", "Supermarket", "", 300),
        ("Rice vinegar", "", 5, "1 tbsp", "Brightens sauces, pickles and sushi rice.", "Supermarket", "", 200),
        ("Balsamic vinegar", "", 15, "1 tbsp", "Sweet-sour for salads, strawberries, chicken.", "Supermarket", "", 400),
        ("Ketjap manis", "", 40, "1 tsp", "Sweet soy for nasi goreng and satay.", "Kaldi", "soy, wheat", 450),
        ("Sambal oelek", "", 5, "1 tsp", "Fresh chili paste for anything.", "Kaldi", "", 400),
        ("Tzatziki (tub)", "", 20, "1 tbsp", "Ready-made yogurt dip.", "Costco", "dairy", 600),
    ]),
    ("spice", "Spices & blends", "", "", [
        ("Black pepper (coarse)", "", 3, "1 tsp", "Fresh-ground, on everything.", "Supermarket", "", 200),
        ("Chili flakes", "", 6, "1 tsp", "Heat for pasta, pizza, eggs.", "Supermarket", "", 200),
        ("Turmeric", "", 8, "1 tsp", "Color and earthiness for curries and rice.", "Supermarket", "", 250),
        ("Coriander seed", "", 5, "1 tsp", "Citrusy spice for curries and rubs.", "Supermarket", "", 300),
        ("Curry powder", "", 8, "1 tsp", "Instant curry flavour, no roux.", "Supermarket", "", 250),
        ("Chili powder blend", "", 8, "1 tsp", "Tex-Mex flavour for beans and mince.", "Supermarket", "", 300),
        ("Oregano", "", 3, "1 tsp", "Pizza, tomato sauces, Greek chicken.", "Supermarket", "", 200),
        ("Italian herbs", "", 3, "1 tsp", "Mixed herbs for pasta and roast chicken.", "Supermarket", "", 250),
        ("Rosemary", "", 3, "1 tsp", "Roast potatoes and chicken.", "Supermarket", "", 250),
        ("Thyme", "", 3, "1 tsp", "Stews, mushrooms, chicken.", "Supermarket", "", 250),
        ("Basil (dried)", "", 2, "1 tsp", "Tomato sauces and soups.", "Supermarket", "", 200),
        ("Dill", "", 2, "1 tsp", "Fish, yogurt sauces, potatoes.", "Supermarket", "", 250),
        ("Cinnamon", "", 6, "1 tsp", "Oats, yogurt, coffee, Moroccan stews.", "Supermarket", "", 200),
        ("Five-spice powder", "", 6, "1 tsp", "Chinese roast pork and duck flavour.", "Kaldi", "", 350),
        ("Ginger powder", "", 6, "1 tsp", "Quick ginger for marinades.", "Supermarket", "", 200),
        ("Onion powder", "", 8, "1 tsp", "Savory base for rubs and dips.", "Supermarket", "", 250),
        ("Lemon pepper", "", 3, "1 tsp", "Bright seasoning for fish and chicken.", "Supermarket", "", 300),
        ("Everything bagel seasoning", "", 10, "1 tsp", "On eggs, avocado, cottage cheese.", "Kaldi", "sesame", 500),
        ("Taco seasoning", "", 10, "1 tsp", "Mince, chicken, beans in one shake.", "Supermarket", "", 150),
        ("Jerk seasoning", "", 6, "1 tsp", "Caribbean spice for chicken thighs.", "Kaldi", "", 450),
        ("Ras el hanout", "", 6, "1 tsp", "Moroccan blend for chickpeas and lamb.", "Kaldi", "", 500),
        ("Sumac", "", 5, "1 tsp", "Lemony red spice for salads and chicken.", "Kaldi", "", 500),
        ("Tandoori masala", "", 6, "1 tsp", "Mix with yogurt for tandoori chicken.", "Kaldi", "", 400),
        ("Chaat masala", "", 4, "1 tsp", "Tangy salty spice for fruit, eggs, potatoes.", "Asian grocer", "", 400),
        ("Mustard seeds", "", 10, "1 tsp", "Pop in hot oil for Indian dal and veg.", "Asian grocer", "", 300),
        ("Fennel seeds", "", 7, "1 tsp", "Sweet anise flavour for sausage-style meat.", "Kaldi", "", 350),
        ("Yukari (red shiso salt)", "", 3, "1 tsp", "Pink, sour, salty: on rice and cabbage.", "Supermarket", "", 250),
        ("Aonori", "", 2, "1 tsp", "Seaweed flakes for okonomiyaki, fries, eggs.", "Supermarket", "", 250),
        ("Sesame seeds", "", 18, "1 tsp", "Nutty crunch on rice, salads, broccoli.", "Supermarket", "sesame", 150),
        ("MSG / Ajinomoto", "", 0, "pinch", "Pure savory boost for soups and eggs.", "Supermarket", "", 200),
        ("Herb salt", "", 0, "pinch", "Garlic and herb salt for everything.", "Supermarket", "", 250),
        ("Bouillon powder", "", 5, "1 tsp", "Chicken or veg stock for soups and rice.", "Supermarket", "", 250),
    ]),
    ("world", "World flavours", "", "Pick a country, get the taste. Each one turns plain chicken and rice into something else.", [
        ("Korean: gochujang + sesame + garlic", "", 40, "1 tbsp mix", "Bibimbap bowls and spicy pork.", "Supermarket", "soy, wheat, sesame", 400),
        ("Thai: fish sauce + lime + chili", "", 10, "1 tbsp mix", "Larb, Thai beef salad, basil chicken.", "Supermarket", "fish", 300),
        ("Vietnamese: nuoc cham", "", 15, "1 tbsp", "Fish sauce + lime + sweetener + garlic + water. For rice noodle bowls.", "Make it", "fish", 0),
        ("Indian: garam masala + yogurt", "", 20, "1 tbsp mix", "Quick butter-chicken style without the butter.", "Supermarket", "dairy", 350),
        ("Mexican: cumin + lime + chili", "", 8, "1 tsp mix", "Burrito bowls, fajita chicken, beans.", "Supermarket", "", 300),
        ("Greek: oregano + lemon + garlic", "", 5, "1 tsp mix", "Souvlaki chicken, roast potatoes, salads.", "Supermarket", "", 200),
        ("Italian: garlic + basil + tomato", "", 10, "1 tbsp", "Pasta, chicken parm, shakshuka.", "Supermarket", "", 200),
        ("Chinese: soy + ginger + black vinegar", "", 10, "1 tbsp mix", "Dumplings, stir-fries, cold tofu.", "Supermarket", "soy, wheat", 300),
        ("Sichuan: chili + sansho", "", 15, "1 tsp mix", "Numbing heat for mapo tofu and noodles.", "Supermarket", "", 300),
        ("Middle Eastern: za'atar + lemon", "", 10, "1 tsp mix", "Chicken, eggs, yogurt bowls.", "Kaldi", "sesame", 500),
        ("Moroccan: ras el hanout + lemon", "", 8, "1 tsp mix", "Chickpea stew, chicken tagine-style.", "Kaldi", "", 500),
        ("Japanese: miso + mirin + ginger", "", 25, "1 tbsp mix", "Miso salmon, pork, eggplant.", "Supermarket", "soy", 300),
        ("Hawaiian: soy + pineapple + ginger", "", 20, "1 tbsp mix", "Huli huli chicken and poke bowls.", "Supermarket", "soy, wheat", 300),
        ("Peruvian: aji amarillo + lime", "", 10, "1 tsp", "Yellow chili for chicken and potatoes.", "Online", "", 800),
        ("Caribbean: jerk + lime", "", 6, "1 tsp mix", "Jerk chicken thighs with rice and beans.", "Kaldi", "", 450),
        ("Filipino: adobo (soy + vinegar + garlic)", "", 10, "1 tbsp mix", "Chicken or pork adobo, the easiest one-pot.", "Supermarket", "soy, wheat", 250),
    ]),
    ("rub", "Marinades & rubs", "", "Mix the night before, cook straight from the fridge. Nearly zero extra calories.", [
        ("Shio koji chicken", "", 10, "1 tsp per 100 g", "Tender, salty-sweet chicken breast.", "Supermarket", "", 300),
        ("Yogurt tandoori marinade", "", 25, "2 tbsp", "Yogurt + tandoori masala + lemon. Air fry at 200 °C.", "Make it", "dairy", 0),
        ("Soy ginger garlic marinade", "", 15, "1 tbsp", "The everyday Japanese base for pork and chicken.", "Make it", "soy, wheat", 0),
        ("Lemon herb marinade", "", 20, "1 tbsp", "Lemon + garlic + oregano + 1 tsp oil.", "Make it", "", 0),
        ("Smoky BBQ rub", "", 8, "1 tsp", "Paprika + garlic + onion powder + pinch of sweetener.", "Make it", "", 0),
        ("Cajun rub", "", 5, "1 tsp", "Cajun seasoning + garlic: chicken, shrimp, potatoes.", "Make it", "", 0),
        ("Mojo marinade", "", 15, "1 tbsp", "Orange + lime + garlic + cumin + oregano for pork.", "Make it", "", 0),
        ("Bulgogi marinade (light)", "", 20, "1 tbsp", "Soy + grated pear or apple + garlic + sesame.", "Make it", "soy, wheat, sesame", 0),
        ("Miso marinade", "", 20, "1 tbsp", "Miso + mirin, for salmon or pork overnight.", "Make it", "soy", 0),
        ("Salt + pepper + garlic (SPG)", "", 3, "1 tsp", "The rub that works on literally everything.", "Make it", "", 0),
    ]),
    ("crunch", "Toppings & crunch", "", "Texture makes food feel bigger. A spoon of these goes a long way.", [
        ("Fried onions (crispy)", "", 30, "1 tbsp", "On rice, curry, salads. Measure, they add up.", "Supermarket", "wheat", 250),
        ("Toasted sesame seeds", "", 18, "1 tsp", "Rice bowls and greens.", "Supermarket", "sesame", 150),
        ("Nori strips", "", 2, "a handful", "Rice, noodles, eggs.", "Supermarket", "", 200),
        ("Crushed peanuts", "", 30, "1 tsp", "Pad thai, salads, noodles.", "Supermarket", "peanut", 250),
        ("Panko (toasted)", "", 20, "1 tbsp", "Dry-toast in a pan for crunch on pasta and fish.", "Supermarket", "wheat", 200),
        ("Pickled ginger", "", 5, "1 tbsp", "Fresh bite with fish, rice bowls.", "Supermarket", "", 150),
        ("Pickled red onion", "", 5, "2 tbsp", "Onion + vinegar + salt, 30 minutes. On tacos and bowls.", "Make it", "", 0),
        ("Kimchi", "", 10, "30 g", "Crunch + sour heat on eggs, rice, noodles.", "Supermarket", "fish, shellfish", 300),
        ("Green onion", "", 3, "1 tbsp", "Fresh on everything.", "Supermarket", "", 100),
        ("Fresh cilantro or parsley", "", 1, "a handful", "Bright finish for bowls and stews.", "Supermarket", "", 150),
        ("Lemon or lime wedge", "", 3, "1 wedge", "A squeeze at the end wakes up any dish.", "Supermarket", "", 50),
        ("Takuan (yellow radish)", "", 5, "3 slices", "Sweet-sour crunch with rice.", "Supermarket", "", 200),
    ]),
    ("dips", "Dips & spreads", "", "For veggie sticks, wraps and toast.", [
        ("Hummus", "", 50, "2 tbsp", "Chickpea dip for wraps and veg. Make it with less tahini.", "Kaldi", "sesame", 500),
        ("Cottage cheese dip", "", 25, "2 tbsp", "Blend cottage cheese + garlic + herbs. High protein.", "Make it", "dairy", 0),
        ("Guacamole", "", 45, "2 tbsp", "Avocado + lime + onion + salt.", "Make it", "", 0),
        ("Baba ganoush", "", 25, "2 tbsp", "Smoky eggplant dip.", "Make it", "sesame", 0),
        ("Tuna yogurt spread", "", 30, "2 tbsp", "Canned tuna + yogurt + mustard. Toast or onigiri filling.", "Make it", "fish, dairy", 0),
        ("Edamame dip", "", 30, "2 tbsp", "Blend edamame + lemon + garlic. Green hummus.", "Make it", "soy", 0),
        ("Salsa roja", "", 5, "2 tbsp", "Blended roasted tomato + chili.", "Make it", "", 0),
        ("Natto mustard", "", 5, "1 pack sauce", "Comes with the natto: mix in, top rice.", "Supermarket", "soy", 0),
    ]),
]


def merged(base):
    """library.TASTE_GUIDE plus EXTRA_GUIDE, without duplicate names."""
    by_key = {key: [key, title, jp, blurb, list(items)] for key, title, jp, blurb, items in base}
    order = [key for key, *_ in base]
    for key, title, jp, blurb, items in EXTRA_GUIDE:
        if key not in by_key:
            by_key[key] = [key, title, jp, blurb, []]
            order.append(key)
        have = {i[0].lower() for i in by_key[key][4]}
        by_key[key][4] += [i for i in items if i[0].lower() not in have]
    return [tuple(by_key[k][:4]) + (by_key[k][4],) for k in order]
